#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDCF91FB242ACED (erikd@mega-nerd.com)
#
Name     : libsndfile
Version  : 1.0.28
Release  : 20
URL      : http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28.tar.gz
Source0  : http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28.tar.gz
Source99 : http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28.tar.gz.asc
Summary  : A library for reading and writing audio files
Group    : Development/Tools
License  : LGPL-2.1
Requires: libsndfile-bin
Requires: libsndfile-lib
Requires: libsndfile-doc
BuildRequires : alsa-lib-dev
BuildRequires : alsa-lib-dev32
BuildRequires : flac-dev
BuildRequires : flac-dev32
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : libogg-dev
BuildRequires : libogg-dev32
BuildRequires : libvorbis-dev
BuildRequires : libvorbis-dev32
BuildRequires : sed
BuildRequires : sqlite-autoconf-dev
BuildRequires : sqlite-autoconf-dev32
Patch1: cve-2017-8361.nopatch
Patch2: cve-2017-8363.nopatch
Patch3: cve-2017-8365.patch
Patch4: cve-2017-8362.patch
Patch5: cve-2017-6892.patch
Patch6: CVE-2017-12562.patch
Patch7: cve-2017-14245.patch
Patch8: cve-2017-14634.patch
Patch9: cve-2017-14246.nopatch

%description
This is libsndfile, 1.0.28
libsndfile is a library of C routines for reading and writing
files containing sampled audio data.

%package bin
Summary: bin components for the libsndfile package.
Group: Binaries

%description bin
bin components for the libsndfile package.


%package dev
Summary: dev components for the libsndfile package.
Group: Development
Requires: libsndfile-lib
Requires: libsndfile-bin
Provides: libsndfile-devel

%description dev
dev components for the libsndfile package.


%package dev32
Summary: dev32 components for the libsndfile package.
Group: Default
Requires: libsndfile-lib32
Requires: libsndfile-bin
Requires: libsndfile-dev

%description dev32
dev32 components for the libsndfile package.


%package doc
Summary: doc components for the libsndfile package.
Group: Documentation

%description doc
doc components for the libsndfile package.


%package lib
Summary: lib components for the libsndfile package.
Group: Libraries

%description lib
lib components for the libsndfile package.


%package lib32
Summary: lib32 components for the libsndfile package.
Group: Default

%description lib32
lib32 components for the libsndfile package.


%prep
%setup -q -n libsndfile-1.0.28
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1
%patch8 -p1
pushd ..
cp -a libsndfile-1.0.28 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1506615104
export CFLAGS="$CFLAGS -fstack-protector-strong "
export FCFLAGS="$CFLAGS -fstack-protector-strong "
export FFLAGS="$CFLAGS -fstack-protector-strong "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong "
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1506615104
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install
## make_install_append content
rm -f %{buildroot}/usr/include/sndfile.hh
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/sndfile-cmp
/usr/bin/sndfile-concat
/usr/bin/sndfile-convert
/usr/bin/sndfile-deinterleave
/usr/bin/sndfile-info
/usr/bin/sndfile-interleave
/usr/bin/sndfile-metadata-get
/usr/bin/sndfile-metadata-set
/usr/bin/sndfile-play
/usr/bin/sndfile-regtest
/usr/bin/sndfile-salvage

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libsndfile.so
/usr/lib64/pkgconfig/sndfile.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libsndfile.so
/usr/lib32/pkgconfig/32sndfile.pc
/usr/lib32/pkgconfig/sndfile.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libsndfile/*
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsndfile.so.1
/usr/lib64/libsndfile.so.1.0.28

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libsndfile.so.1
/usr/lib32/libsndfile.so.1.0.28
